apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  ENTRYPOINT_DEBUG: ""
  DATABASE_TABLE_KEYS: {{ quote (coalesce .Values.database.table_dkim_keys (print (.Values.name | replace "-" "_") "_keys")) }}
  DATABASE_TABLE_SIGNING: {{ quote (coalesce .Values.database.table_dkim_signing (print (.Values.name | replace "-" "_") "_signing_table")) }}
  RELAY_NETS: "{{ .Values.opendkim.relay_nets }}"

